In [1]:
import numpy as np
myarr=np.array([[3,6,37,7]],np.int64)
myarr[0,1]

6

In [2]:
myarr.shape

(1, 4)

In [4]:
myarr.dtype

dtype('int64')

In [6]:
myarr[0,1]=45
myarr #We replaced the value of 6 with 45

array([[ 3, 45, 37,  7]], dtype=int64)

# Array creation : Conversion from other python structures

In [7]:
listarray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [8]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print(listarray.dtype)
print(listarray.shape)
print(listarray.size)


int32
(3, 3)
9


In [13]:
zeros=np.zeros((2,5)) #It basically created an 2,5 sized array full of zeroes in it

In [14]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
rng=np.arange(15) #It created an array in the range of 0 to 15

In [18]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace=np.linspace(1,4,10)
lspace

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [23]:
emp=np.empty((4,6)) #It created an array of 4,6 with an empty array with all the values in it being completely random

In [24]:
emp

array([[4.67296746e-307, 1.69121096e-306, 2.22519779e-307,
        1.33511018e-306, 1.33511969e-306, 6.23037996e-307],
       [6.23053954e-307, 9.34609790e-307, 8.45593934e-307,
        9.34600963e-307, 1.86921143e-306, 6.23061763e-307],
       [8.90104239e-307, 6.89804132e-307, 1.33512376e-306,
        6.89806849e-307, 9.34609790e-307, 1.69121096e-306],
       [1.05700515e-307, 2.04712906e-306, 7.56589622e-307,
        1.11258277e-307, 8.90111708e-307, 2.12203497e-312]])

In [25]:
ide=np.identity(45)

In [26]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [27]:
arr2=np.arange(99)

In [28]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr2.reshape(3,33) #So it reshaped it into 3,33 version

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
arr=arr2.ravel()

In [ ]:
arr #So it again reformed into a 1 D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [34]:
arr.shape

(99,)

In [35]:
x=[[1,2,3],[4,5,6],[7,8,9]]

In [36]:
ar=np.array(x)

In [37]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [38]:
ar.sum(axis=0) #It adds the array along the columns as an axis 0 is the column wise accessed axis

array([12, 15, 18])

In [40]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [42]:
ar.T #It transposed the matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [45]:
for item in ar.flat:
    print(item) #ar.flat prints all the elements of the array in the opened form not in the matrix form

1
2
3
4
5
6
7
8
9


In [47]:
ar.ndim #It tells us how many dimensions there are in the array

2

In [50]:
one=np.array([1,2,3,356,7])
one.argmax() #It tells us the index position of the element which is max in the current array

3

In [51]:
one.argmin()

0

In [52]:
one.argsort()

array([0, 1, 2, 4, 3], dtype=int64)

In [53]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
ar.argmin()

0

In [55]:
ar.argmax()

8

In [57]:
ar.argmax(axis=0) #It tells us all the max elements of axis 0's index position

array([2, 2, 2], dtype=int64)

In [58]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [60]:
print(ar.argsort(axis=0))
ar.argsort(axis=1)

[[0 0 0]
 [1 1 1]
 [2 2 2]]


array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [63]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
ar.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

Similarly obviously you can do matrix addition,
matrix subtraction,
matrix multiplication,
and matrix squareroot (sqrt method)